force-app/main/default/objects/Quiz_Admin_User__c/Quiz_Admin_User__c.object-meta.xml
<CustomObject>
    <label>Quiz_Admin_User</label>
    <nameField>
        <label>Quiz_Admin_User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz_Admin_Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Admin_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quiz_Answer__c/Quiz_Answer__c.object-meta.xml
<CustomObject>
    <label>Quiz_Answer</label>
    <nameField>
        <displayFormat>Ans-{000000}</displayFormat>
        <label>Quiz_Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz_Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quiz_Answer__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quiz_Answer__c/fields/isTrue__c.field-meta.xml
<CustomField>
    <fullName>isTrue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isTrue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quiz_Answer__c/fields/Quiz_Question__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz_Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Quiz_Answers</relationshipLabel>
    <relationshipName>Quiz_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Assessment_Name__c/Quiz_Assessment_Name__c.object-meta.xml
<CustomObject>
    <label>Quiz_Assessment_Name</label>
    <nameField>
        <label>Quiz_Assessment_Name Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz_Assessment_Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Assessment_Name__c/fields/Quiz_Admin_User__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Admin_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz_Admin_User</label>
    <referenceTo>Quiz_Admin_User__c</referenceTo>
    <relationshipLabel>Quiz_Assessment_Names</relationshipLabel>
    <relationshipName>Quiz_Assessment_Names</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz_Question</label>
    <nameField>
        <displayFormat>Q-{0000000}</displayFormat>
        <label>Quiz_Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz_Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Question__c/fields/isMultiAnswer__c.field-meta.xml
<CustomField>
    <fullName>isMultiAnswer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isMultiAnswer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quiz_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quiz_Question__c/fields/Quiz_Assessment_Name__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Assessment_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz_Assessment_Name</label>
    <referenceTo>Quiz_Assessment_Name__c</referenceTo>
    <relationshipLabel>Quiz_Questions</relationshipLabel>
    <relationshipName>Quiz_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/Quiz_Result__c.object-meta.xml
<CustomObject>
    <label>Quiz_Result</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Quiz_Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz_Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Result__c/fields/JSON_Result__c.field-meta.xml
<CustomField>
    <fullName>JSON_Result__c</fullName>
    <label>JSON Result</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/Quiz_Session__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz_Session</label>
    <referenceTo>Quiz_Session__c</referenceTo>
    <relationshipLabel>Quiz_Results</relationshipLabel>
    <relationshipName>Quiz_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/Quiz_User__c.field-meta.xml
<CustomField>
    <fullName>Quiz_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz_User</label>
    <referenceTo>Quiz_User__c</referenceTo>
    <relationshipLabel>Quiz_Results</relationshipLabel>
    <relationshipName>Quiz_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Session__c/Quiz_Session__c.object-meta.xml
<CustomObject>
    <label>Quiz_Session</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Quiz_Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz_Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Session__c/fields/isResultPublished__c.field-meta.xml
<CustomField>
    <fullName>isResultPublished__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isResultPublished?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quiz_Session__c/fields/Quiz_Assessment_Name__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Assessment_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz_Assessment_Name</label>
    <referenceTo>Quiz_Assessment_Name__c</referenceTo>
    <relationshipLabel>Quiz_Sessions</relationshipLabel>
    <relationshipName>Quiz_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Session__c/fields/Session_Join_Code__c.field-meta.xml
<CustomField>
    <fullName>Session_Join_Code__c</fullName>
    <label>Session Join Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quiz_Session__c/fields/Session_Name__c.field-meta.xml
<CustomField>
    <fullName>Session_Name__c</fullName>
    <label>Session Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quiz_Session__c/fields/Session_Status__c.field-meta.xml
<CustomField>
    <fullName>Session_Status__c</fullName>
    <label>Session Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initialize</fullName>
                <default>true</default>
                <label>Initialize</label>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quiz_Session__c/fields/Session_Time_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Session_Time_Minutes__c</fullName>
    <label>Session Time(Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quiz_User__c/Quiz_User__c.object-meta.xml
<CustomObject>
    <label>Quiz_User</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>Quiz_User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz_Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_User__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Full Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quiz_User__c/fields/Quiz_Session__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz_Session</label>
    <referenceTo>Quiz_Session__c</referenceTo>
    <relationshipLabel>Quiz_Users</relationshipLabel>
    <relationshipName>Quiz_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_User__c/fields/Total_Tab_Switched__c.field-meta.xml
<CustomField>
    <fullName>Total_Tab_Switched__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Tab Switched</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Quiz_SessionResultCtrl.cls
public without sharing class Quiz_SessionResultCtrl {
    @AuraEnabled
    public static WrapperStudentDetails getStudentResultPayload(String studentId, String assessmentId) {
        WrapperStudentDetails wrpObj = new WrapperStudentDetails();
        Quiz_User__c qUser = new Quiz_User__c();
        List<WrapperQuestion> wrpQuesList = new List<WrapperQuestion>();
        List<Quiz_Result__c> qResult = new List<Quiz_Result__c>();
        Quiz_Assessment_Name__c assName = [SELECT Id, Name, Quiz_Admin_User__c FROM Quiz_Assessment_Name__c WHERE Id=:assessmentId Limit 1];
        List<Quiz_Question__c> questionList = new List<Quiz_Question__c>();
        List<Quiz_Answer__c> answerList = new List<Quiz_Answer__c>();
        Map<String, List<WrapperAnswer>> questionAnswerMap = new Map<String, List<WrapperAnswer>>();
        Integer questionIndex = 1;
        Map<String,Boolean> answerIdAndIsCorrectMap = new Map<String,Boolean>();
        Integer corrAns = 0;
        Integer sessionTotalQuestion = 0;

        qUser = [SELECT Id, Full_Name__c, Email__c FROM Quiz_User__c WHERE Id=:studentId Limit 1];
        qResult = [SELECT Id,JSON_Result__c,Quiz_User__c FROM Quiz_Result__c WHERE Quiz_User__c =: studentId];
        questionList = [SELECT Id, Question__c, Quiz_Assessment_Name__c, isMultiAnswer__c FROM Quiz_Question__c WHERE Quiz_Assessment_Name__c=:assessmentId ORDER BY CreatedDate ASC];
        answerList = [SELECT Id, Index__c, Answer__c, isTrue__c, Quiz_Question__c FROM Quiz_Answer__c WHERE Quiz_Question__c in:questionList ORDER BY CreatedDate ASC];
        sessionTotalQuestion = questionList.size();
        
        system.debug('qResult.size--->'+qResult.size());
        if(qResult.size()>0){
            List<WrapperQuestion> objResultList = (List<WrapperQuestion>) JSON.deserialize(qResult[0].JSON_Result__c, List<WrapperQuestion>.class);
            corrAns = getCorrectAnsCount(objResultList);
            for(WrapperQuestion wQues : objResultList){
                for(WrapperAnswer wAns : wQues.answerList){
                    If(wAns.isSelected == true){
                        if(wAns.isTrue){
                            answerIdAndIsCorrectMap.put(wAns.answerId, true);
                        }
                        else{
                             answerIdAndIsCorrectMap.put(wAns.answerId, false);
                        }
                    }
                }
            }
        }
        
        for(Quiz_Answer__c ans : answerList){
            if(!questionAnswerMap.containsKey(ans.Quiz_Question__c)){
                questionAnswerMap.put(ans.Quiz_Question__c, new List<WrapperAnswer>());
            }
            List<WrapperAnswer> answerList1 = questionAnswerMap.get(ans.Quiz_Question__c);
            WrapperAnswer wrpAns = new WrapperAnswer();
            wrpAns.answerIndex = ans.Index__c;
            wrpAns.answerId = ans.Id;
            wrpAns.answerName = ans.Answer__c;
            wrpAns.isTrue = ans.isTrue__c;
            if(answerIdAndIsCorrectMap.containsKey(ans.Id)){
                //wrpAns.style = answerIdAndIsCorrectMap.get(ans.Id) == true ? 'background-color: rgb(132, 222, 132);' : 'background-color: rgb(240, 140, 140);';
                wrpAns.className = answerIdAndIsCorrectMap.get(ans.Id) == true ? 'right-answer' : 'wrong-answer';
            }
            answerList1.add(wrpAns);
            questionAnswerMap.put(ans.Quiz_Question__c, answerList1);
        }

        wrpObj.assessmentName = assName.Name;
        wrpObj.studentName = qUser.Full_Name__c;
        wrpObj.studentEmail = qUser.Email__c;
        wrpObj.correctAnswer = String.valueof(corrAns)+'/'+String.valueof(sessionTotalQuestion);
        Decimal resPer = (Decimal.valueof(corrAns)*100)/Decimal.valueof(sessionTotalQuestion);
        wrpObj.percentage = String.valueof(resPer.setScale(2))+'%';
        wrpObj.greetUser = 'Hello '+qUser.Full_Name__c+',';
        for(Quiz_Question__c ques : questionList){
            WrapperQuestion wrpQues = new WrapperQuestion();
            wrpQues.questionIndex = String.valueof(questionIndex);
            wrpQues.questionName = ques.Question__c;
            wrpQues.isMultiAnswer = ques.isMultiAnswer__c;
            wrpQues.quesId = ques.Id;
            wrpQues.answerList = questionAnswerMap.get(ques.Id);
            wrpQuesList.add(wrpQues);
            questionIndex ++;
        }
        wrpObj.totalQuestion = String.valueof(wrpQuesList.size());
        wrpObj.questionList = wrpQuesList;

        return wrpObj;
    }
    public class WrapperStudentDetails{
		@AuraEnabled public String assessmentName='';
        @AuraEnabled public String totalQuestion='';
        @AuraEnabled public String studentName='';
        @AuraEnabled public String studentEmail='';
        @AuraEnabled public String greetUser='';
        @AuraEnabled public String correctAnswer='';
        @AuraEnabled public String percentage='';
        @AuraEnabled public String sessionName='';
        @AuraEnabled public String sessionTime='';
        @AuraEnabled public List<WrapperQuestion> questionList=new List<WrapperQuestion>();
	}

    @AuraEnabled
    public static void publishResultDB(String sessionId) {
        Quiz_Session__c sessionRec = [SELECT Id,isResultPublished__c,Quiz_Assessment_Name__c,Session_Name__c,Session_Status__c,Session_Time_Minutes__c FROM Quiz_Session__c WHERE Id =: sessionId];

        sessionRec.isResultPublished__c = true;
        update sessionRec;
    }

    @AuraEnabled
    public static WrapperStudentDetails studentResultPayload(String sessionCode, String studentEmail) {
        WrapperStudentDetails wrd = new WrapperStudentDetails();
        String studentId = '';
        List<Quiz_Session__c> sessionRec = new List<Quiz_Session__c>();
        List<Quiz_User__c> studentRec = new List<Quiz_User__c>();
        Integer intJoinCode = Integer.valueof(sessionCode);

        sessionRec = [SELECT Id,Session_Name__c,Session_Time_Minutes__c,Quiz_Assessment_Name__c,Session_Join_Code__c,isResultPublished__c FROM Quiz_Session__c WHERE Session_Join_Code__c=:intJoinCode Limit 1];

        if(sessionRec.size()>0){
            studentRec = [Select Id,Email__c From Quiz_User__c Where Email__c =:studentEmail AND Quiz_Session__c =:sessionRec[0].Id];
            if(studentRec.size()>0){
                wrd = getStudentResultPayload(studentRec[0].Id, sessionRec[0].Quiz_Assessment_Name__c);
                wrd.sessionName = sessionRec[0].Session_Name__c;
                wrd.sessionTime = String.valueof(sessionRec[0].Session_Time_Minutes__c)+' Minutes';
            }
        }

        return wrd;
    }
    

    @AuraEnabled
    public static WrapperResult getSessionResultPayload(String sessionId) {
        WrapperResult wResult = new WrapperResult();
        List<WrapperStudent> studentList=new List<WrapperStudent>();
        List<Quiz_User__c> sessionUserList = new List<Quiz_User__c>();
        List<Quiz_Result__c> sessionResultList = new List<Quiz_Result__c>();
        Map<Id,Quiz_Result__c> userIdResultMap = new Map<Id,Quiz_Result__c>();
        List<Quiz_Question__c> sessionQuestionList = new List<Quiz_Question__c>();
        Integer sessionTotalQuestion = 0;
        Integer indexCount = 1;
        Quiz_Session__c sessionRec = [SELECT Id,Session_Join_Code__c,isResultPublished__c,Quiz_Assessment_Name__c,Session_Name__c,Session_Status__c,Session_Time_Minutes__c FROM Quiz_Session__c WHERE Id =: sessionId];
        wResult.sessionId = sessionId;
        wResult.quizCode = String.valueof(sessionRec.Session_Join_Code__c);
        wResult.sessionName = sessionRec.Session_Name__c;
        wResult.sessionStatus = sessionRec.Session_Status__c;
        wResult.sessionTime = String.valueof(sessionRec.Session_Time_Minutes__c);
        wResult.isPublished = sessionRec.isResultPublished__c;

        sessionUserList = [SELECT Id,Full_Name__c,Email__c,Total_Tab_Switched__c FROM Quiz_User__c WHERE Quiz_Session__c =: sessionId];
        sessionResultList = [SELECT Id,JSON_Result__c,Quiz_User__c FROM Quiz_Result__c WHERE Quiz_Session__c =: sessionId];
        sessionQuestionList = [SELECT Id FROM Quiz_Question__c WHERE Quiz_Assessment_Name__c =: sessionRec.Quiz_Assessment_Name__c];
        sessionTotalQuestion = sessionQuestionList.size();

        for(Quiz_Result__c qr : sessionResultList){
            userIdResultMap.put(qr.Quiz_User__c, qr);
        }
        for(Quiz_User__c qUser : sessionUserList){
            WrapperStudent ws = new WrapperStudent();
            ws.studentId = qUser.Id;
            ws.position = String.valueof(indexCount);
            ws.studentName = qUser.Full_Name__c;
            ws.totalTabSwitch = String.valueof(qUser.Total_Tab_Switched__c);
            ws.studentEmail = qUser.Email__c;
            ws.studentCorrectAnswer = '0';
            ws.studentResulPercentage = '0%';
            if(userIdResultMap.containsKey(qUser.Id)){
                Integer corrAns = 0;
                Quiz_Result__c qr = userIdResultMap.get(qUser.Id); 
                List<WrapperQuestion> objResultList = (List<WrapperQuestion>) JSON.deserialize(qr.JSON_Result__c, List<WrapperQuestion>.class);
                corrAns = getCorrectAnsCount(objResultList);
                /*for(WrapperQuestion wQues : objResultList){
                    Boolean trueFlag  = false;
                    for(WrapperAnswer wAns : wQues.answerList){
                        if(wAns.isTrue == true){
                            if(wAns.isSelected == false){
                                trueFlag = false;
                                break;
                            }
                            else{
                                trueFlag = true;
                            }
                        }
                        else{
                            if(wAns.isSelected == true){
                                trueFlag = false;
                                break;
                            }
                            else{
                                trueFlag = true;
                            }
                        }
                    }
                    if(trueFlag){
                        corrAns = corrAns + 1;
                    }
                }*/
                ws.studentCorrectAnswer = String.valueof(corrAns)+'/'+String.valueof(sessionTotalQuestion);
                Decimal resPer = (Decimal.valueof(corrAns)*100)/Decimal.valueof(sessionTotalQuestion);
                ws.studentResulPercentage = String.valueof(resPer.setScale(2))+'%';
            }
            studentList.add(ws);
            indexCount = indexCount+1;
        }
        wResult.studentList = studentList;
        return wResult;
    }

    public static Integer getCorrectAnsCount(List<WrapperQuestion> objResultList){
        Integer corrAns = 0;
        for(WrapperQuestion wQues : objResultList){
            Boolean trueFlag  = false;
            for(WrapperAnswer wAns : wQues.answerList){
                if(wAns.isTrue == true){
                    if(wAns.isSelected == false){
                        trueFlag = false;
                        break;
                    }
                    else{
                        trueFlag = true;
                    }
                }
                else{
                    if(wAns.isSelected == true){
                        trueFlag = false;
                        break;
                    }
                    else{
                        trueFlag = true;
                    }
                }
            }
            if(trueFlag){
                corrAns = corrAns + 1;
            }
        }
        return corrAns;
    }

    public class WrapperResult{
        @AuraEnabled public String sessionId='';
        @AuraEnabled public String quizCode='';
		@AuraEnabled public String sessionName='';
        @AuraEnabled public String sessionStatus='';
        @AuraEnabled public String sessionTime='';
        @AuraEnabled public Boolean isPublished=true;
        @AuraEnabled public List<WrapperStudent> studentList=new List<WrapperStudent>();
	}
    public class WrapperStudent{
        @AuraEnabled public String studentId='';
        @AuraEnabled public String position='';
		@AuraEnabled public String studentName='';
        @AuraEnabled public String totalTabSwitch='';
        @AuraEnabled public String studentEmail='';
        @AuraEnabled public String studentCorrectAnswer='';
        @AuraEnabled public String studentResulPercentage='';
	}
    
    public class WrapperQuestion{
        @AuraEnabled public String questionIndex='0';
        @AuraEnabled public String quesId='';
        @AuraEnabled public String error;
		@AuraEnabled public String questionName='';
		@AuraEnabled public Boolean isMultiAnswer=false;
        @AuraEnabled public String finalQuestion='';
        @AuraEnabled public String filterMesage='';
        @AuraEnabled public List<WrapperAnswer> answerList=new List<WrapperAnswer>();
	}
    public class WrapperAnswer{
        @AuraEnabled public String answerId='';
		@AuraEnabled public String answerName='';
        @AuraEnabled public String answerIndex='';
		@AuraEnabled public Boolean isTrue=false;
        @AuraEnabled public Boolean isSelected=false;
        //@AuraEnabled public String style='';
        @AuraEnabled public String className='';
	}
}