force-app/main/default/objects/Quiz_Admin_User__c/Quiz_Admin_User__c.object-meta.xml
<CustomObject>
    <label>Quiz_Admin_User</label>
    <nameField>
        <label>Quiz_Admin_User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz_Admin_Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Admin_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quiz_Admin_User__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quiz_Admin_User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Quiz_Login.cls
/**
* @File Name : Quiz_Login.cls
* @Description :
* @Author : Debabrata Ghosh
* @Last Modified By :
* @Last Modified On : January 30, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | January 30, 2025 |   | Initial Version
**/

public without sharing class Quiz_Login {
	@AuraEnabled
	public static WrapperObject loginValidate(String email, String password){
		System.debug('email->'+email+'  pass->'+password);
		WrapperObject retVal = new WrapperObject();
		List<Quiz_Admin_User__c> adminUserList = new List<Quiz_Admin_User__c>();

		adminUserList = [Select Id,Name From Quiz_Admin_User__c Where Email__c=:email AND Password__c=:password AND isActive__c=true Limit 1];

		if(adminUserList.size()>0){
			retVal.userId = adminUserList[0].Id;
			retVal.userName = adminUserList[0].Name;
			retVal.greetUser = 'Hello '+adminUserList[0].Name+',';
		}
		else{
			retVal.error = 'user not found';
		}

		return retVal;
	}

	public class WrapperObject{
		@AuraEnabled public String userId='';
		@AuraEnabled public String userName='';
		@AuraEnabled public String greetUser='';
		@AuraEnabled public String error;
	}
}