force-app/main/default/objects/Quiz_Admin_User__c/Quiz_Admin_User__c.object-meta.xml
<CustomObject>
    <label>Quiz_Admin_User</label>
    <nameField>
        <label>Quiz_Admin_User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz_Admin_Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Admin_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quiz_Answer__c/Quiz_Answer__c.object-meta.xml
<CustomObject>
    <label>Quiz_Answer</label>
    <nameField>
        <displayFormat>Ans-{000000}</displayFormat>
        <label>Quiz_Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz_Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quiz_Answer__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quiz_Answer__c/fields/isTrue__c.field-meta.xml
<CustomField>
    <fullName>isTrue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isTrue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quiz_Answer__c/fields/Quiz_Question__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz_Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Quiz_Answers</relationshipLabel>
    <relationshipName>Quiz_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Assessment_Name__c/Quiz_Assessment_Name__c.object-meta.xml
<CustomObject>
    <label>Quiz_Assessment_Name</label>
    <nameField>
        <label>Quiz_Assessment_Name Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz_Assessment_Names</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Assessment_Name__c/fields/Quiz_Admin_User__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Admin_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz_Admin_User</label>
    <referenceTo>Quiz_Admin_User__c</referenceTo>
    <relationshipLabel>Quiz_Assessment_Names</relationshipLabel>
    <relationshipName>Quiz_Assessment_Names</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz_Question</label>
    <nameField>
        <displayFormat>Q-{0000000}</displayFormat>
        <label>Quiz_Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz_Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Question__c/fields/isMultiAnswer__c.field-meta.xml
<CustomField>
    <fullName>isMultiAnswer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isMultiAnswer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quiz_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quiz_Question__c/fields/Quiz_Assessment_Name__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Assessment_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz_Assessment_Name</label>
    <referenceTo>Quiz_Assessment_Name__c</referenceTo>
    <relationshipLabel>Quiz_Questions</relationshipLabel>
    <relationshipName>Quiz_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/Quiz_Result__c.object-meta.xml
<CustomObject>
    <label>Quiz_Result</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Quiz_Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz_Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Result__c/fields/JSON_Result__c.field-meta.xml
<CustomField>
    <fullName>JSON_Result__c</fullName>
    <label>JSON Result</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/Quiz_Session__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz_Session</label>
    <referenceTo>Quiz_Session__c</referenceTo>
    <relationshipLabel>Quiz_Results</relationshipLabel>
    <relationshipName>Quiz_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Result__c/fields/Quiz_User__c.field-meta.xml
<CustomField>
    <fullName>Quiz_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz_User</label>
    <referenceTo>Quiz_User__c</referenceTo>
    <relationshipLabel>Quiz_Results</relationshipLabel>
    <relationshipName>Quiz_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Session__c/Quiz_Session__c.object-meta.xml
<CustomObject>
    <label>Quiz_Session</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Quiz_Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz_Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Session__c/fields/isResultPublished__c.field-meta.xml
<CustomField>
    <fullName>isResultPublished__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isResultPublished?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quiz_Session__c/fields/Quiz_Assessment_Name__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Assessment_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz_Assessment_Name</label>
    <referenceTo>Quiz_Assessment_Name__c</referenceTo>
    <relationshipLabel>Quiz_Sessions</relationshipLabel>
    <relationshipName>Quiz_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Session__c/fields/Session_Join_Code__c.field-meta.xml
<CustomField>
    <fullName>Session_Join_Code__c</fullName>
    <label>Session Join Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quiz_Session__c/fields/Session_Name__c.field-meta.xml
<CustomField>
    <fullName>Session_Name__c</fullName>
    <label>Session Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quiz_Session__c/fields/Session_Status__c.field-meta.xml
<CustomField>
    <fullName>Session_Status__c</fullName>
    <label>Session Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initialize</fullName>
                <default>true</default>
                <label>Initialize</label>
            </value>
            <value>
                <fullName>Running</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quiz_Session__c/fields/Session_Time_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Session_Time_Minutes__c</fullName>
    <label>Session Time(Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quiz_User__c/Quiz_User__c.object-meta.xml
<CustomObject>
    <label>Quiz_User</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>Quiz_User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz_Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_User__c/fields/Another_Tab_Open__c.field-meta.xml
<CustomField>
    <fullName>Another_Tab_Open__c</fullName>
    <defaultValue>false</defaultValue>
    <description>for real-time value</description>
    <label>Another Tab Open?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quiz_User__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Full Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quiz_User__c/fields/Quiz_Session__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quiz_Session</label>
    <referenceTo>Quiz_Session__c</referenceTo>
    <relationshipLabel>Quiz_Users</relationshipLabel>
    <relationshipName>Quiz_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_User__c/fields/Total_Tab_Switched__c.field-meta.xml
<CustomField>
    <fullName>Total_Tab_Switched__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Tab Switched</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Quiz_AdminSessionViewCtrl.cls
/**
* @File Name : Quiz_AdminSessionViewCtrl.cls
* @Description :
* @Author : Debabrata Ghosh
* @Last Modified By :
* @Last Modified On : January 31, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | January 31, 2025 |   | Initial Version
**/

public without sharing class Quiz_AdminSessionViewCtrl {
    @AuraEnabled
	public static wrapperSessionDetails fetchSessionDetails(String sessionId){
        wrapperSessionDetails wsd = new wrapperSessionDetails();
        Quiz_Session__c newSession = new Quiz_Session__c();
        newSession = [SELECT Id,Quiz_Assessment_Name__c,Session_Name__c,Session_Time_Minutes__c,Session_Status__c,Session_Join_Code__c FROM Quiz_Session__c WHERE Id=:sessionId];
        wsd.Id = newSession.Id;
        wsd.Quiz_Assessment_Name = newSession.Quiz_Assessment_Name__c;
        wsd.Session_Name = newSession.Session_Name__c;
        wsd.Session_Time_Minutes = String.valueof(newSession.Session_Time_Minutes__c);
        wsd.Session_Status = newSession.Session_Status__c;
        wsd.Session_Join_Code = String.valueof(newSession.Session_Join_Code__c);

        return wsd;
    }
    public class wrapperSessionDetails{
        @AuraEnabled public String Id='';
        @AuraEnabled public String Quiz_Assessment_Name='';
		@AuraEnabled public String Session_Name='';
		@AuraEnabled public String Session_Time_Minutes='';
        @AuraEnabled public String Session_Status='';
        @AuraEnabled public String Session_Join_Code='';
	}

    @AuraEnabled
	public static void startSession(String sessionId){
        Quiz_Session__c newSession = new Quiz_Session__c();
        newSession.Id= sessionId;
        newSession.Session_Status__c = 'Running';
        update newSession;
    }

    @AuraEnabled
	public static void endSession(String sessionId){
        Quiz_Session__c newSession = new Quiz_Session__c();
        newSession.Id= sessionId;
        newSession.Session_Status__c = 'Completed';
        update newSession;
    }

    @AuraEnabled
	public static List<wrapperJoinee> fetchJoinee(String sessionId){
        Integer indexCount = 1;
        List<wrapperJoinee> joineeList = new List<wrapperJoinee>();
        List<Quiz_User__c> userList = new List<Quiz_User__c>();
        userList = [SELECT Id,Full_Name__c,Email__c,Total_Tab_Switched__c,Another_Tab_Open__c FROM Quiz_User__c WHERE Quiz_Session__c=:sessionId ORDER BY CreatedDate ASC];
        for(Quiz_User__c userRec:userList){
            wrapperJoinee joinee = new wrapperJoinee();
            joinee.userId = userRec.Id;
            joinee.userFullName = userRec.Full_Name__c;
            joinee.userEmail = userRec.Email__c;
            joinee.index = String.valueof(indexCount);
            joinee.userTabChange = String.valueof(userRec.Total_Tab_Switched__c);
            joinee.anotherTabOpen = userRec.Another_Tab_Open__c == true ? 'true' : 'false';
            joinee.tabStyleCss = userRec.Another_Tab_Open__c == true ? 'highlighted-row':'';
            joineeList.add(joinee);
            indexCount = indexCount+1;
        }
        return joineeList;
    }
    public class wrapperJoinee{
        @AuraEnabled public String userId='';
        @AuraEnabled public String index='0';
		@AuraEnabled public String userFullName='';
		@AuraEnabled public String userEmail='';
        @AuraEnabled public String userTabChange='0';
        @AuraEnabled public String anotherTabOpen='false';
        @AuraEnabled public String tabStyleCss='';
	}

    @AuraEnabled
    public static List<wrapperResultReportQuestionWise> resultReportQuestionWise(String sessionId){
        List<wrapperResultReportQuestionWise> resultReportList = new List<wrapperResultReportQuestionWise>();
        Quiz_Session__c session = [SELECT Id,Quiz_Assessment_Name__c, Quiz_Assessment_Name__r.Name, Session_Join_Code__c, Session_Name__c,Session_Status__c, Session_Time_Minutes__c FROM Quiz_Session__c WHERE ID=:sessionId];
        String assessmentID = session.Quiz_Assessment_Name__c;
        Map<ID,Quiz_Question__c> qustionMap = new Map<ID, Quiz_Question__c>( [SELECT ID, Name, Question__c,Quiz_Assessment_Name__c, isMultiAnswer__c,Quiz_Assessment_Name__r.Quiz_Admin_User__r.Name, Quiz_Assessment_Name__r.Name FROM Quiz_Question__c WHERE Quiz_Assessment_Name__c = :assessmentID]);
        Map<ID,Quiz_Answer__c> relatedAnswerListMap = new Map<ID, Quiz_Answer__c>([SELECT ID, Name, Answer__c, Index__c, isTrue__c, Quiz_Question__c FROM Quiz_Answer__c WHERE Quiz_Question__c IN :qustionMap.keySet()]);
        //Map<ID, List<Quiz_Answer__c>> quizIdAnswerListMap = new Map<ID, List<Quiz_Answer__c>>();
        Map<ID, String> quizIdCorrectAnswerMap = new Map<ID, String>();
        //Map<ID, String> userIdQuizIdAndSelectAnswerMap = new Map<ID, String>();
        Map<String,wrapCandidateDetails> UserAndQuizIdAndCandidateResultMap = new Map<String, wrapCandidateDetails>();
        List<Quiz_Result__c> resultList = [SELECT Id,Name, Quiz_User__c, Quiz_User__r.Name,JSON_Result__c, Quiz_User__r.Full_Name__c, Quiz_User__r.Email__c, Quiz_Session__c FROM Quiz_Result__c WHERE Quiz_Session__c = :sessionId];
        List<Quiz_User__c> quizUserList = [Select Id, Full_Name__c From Quiz_User__c Where Quiz_Session__c = :sessionId];
        Integer questionIndexCount = 1;


        // for(Quiz_Answer__c answer : relatedAnswerListMap.values()){
        //     if (!quizIdAnswerListMap.containsKey(answer.Quiz_Question__c))
        //     quizIdAnswerListMap.put(answer.Quiz_Question__c, new List<Quiz_Answer__c>());
        //     quizIdAnswerListMap.get(answer.Quiz_Question__c).add(answer);
        // }

        for(Quiz_Answer__c answer : relatedAnswerListMap.values()){
            if(answer.isTrue__c){
                if (!quizIdCorrectAnswerMap.containsKey(answer.Quiz_Question__c)){
                    quizIdCorrectAnswerMap.put(answer.Quiz_Question__c, answer.Answer__c);
                }
                else{
                    quizIdCorrectAnswerMap.put(answer.Quiz_Question__c, quizIdCorrectAnswerMap.get(answer.Quiz_Question__c) + ';' + answer.Answer__c);
                }
            }
        }

        for(Quiz_Result__c qr : resultList){
            List<Quiz_SessionResultCtrl.WrapperQuestion> objResultList = (List<Quiz_SessionResultCtrl.WrapperQuestion>) JSON.deserialize(qr.JSON_Result__c, List<Quiz_SessionResultCtrl.WrapperQuestion>.class);
            for(Quiz_SessionResultCtrl.WrapperQuestion wrapObj : objResultList){
                wrapCandidateDetails wrapCandidate = new wrapCandidateDetails();
                String userAndQuesId = qr.Quiz_User__c + wrapObj.quesId;
                String selectedAnswerNameCombine = '';
                Boolean trueFlag  = false;
                for(Quiz_SessionResultCtrl.WrapperAnswer wAns : wrapObj.answerList){
                    if(wAns.isSelected){
                        selectedAnswerNameCombine = selectedAnswerNameCombine + relatedAnswerListMap.get(wAns.answerId).Answer__c + ';'; 
                    }
                    if(wAns.isTrue == true){
                        if(wAns.isSelected == false){
                            trueFlag = false;
                            break;
                        }
                        else{
                            trueFlag = true;
                        }
                    }
                    else{
                        if(wAns.isSelected == true){
                            trueFlag = false;
                            break;
                        }
                        else{
                            trueFlag = true;
                        }
                    }
                }
                wrapCandidate.userId = qr.Quiz_User__c;
                wrapCandidate.userFullName = qr.Quiz_User__r.Full_Name__c;
                wrapCandidate.selectedAnswerNameCombine = selectedAnswerNameCombine;
                wrapCandidate.isCorrect = trueFlag == true ? 'true' : 'false';
                UserAndQuizIdAndCandidateResultMap.put(userAndQuesId, wrapCandidate);
            }
        }

        for(Quiz_Question__c quizQues : qustionMap.values()){
            wrapperResultReportQuestionWise wrapResultReport = new wrapperResultReportQuestionWise();
            List<wrapCandidateDetails> candidateDetailsList = new List<wrapCandidateDetails>();
            wrapResultReport.questionIndex = String.valueof(questionIndexCount);
            wrapResultReport.questionId = quizQues.Id;
            wrapResultReport.questionName = quizQues.Question__c;
            wrapResultReport.correctAnswerNameCombine = quizIdCorrectAnswerMap.get(quizQues.Id);
            for(Quiz_User__c qUser : quizUserList){
                wrapCandidateDetails wrapCandidate = new wrapCandidateDetails();
                if(UserAndQuizIdAndCandidateResultMap.containsKey(String.valueof(qUser.Id) + String.valueof(quizQues.Id))){
                    wrapCandidate = UserAndQuizIdAndCandidateResultMap.get(String.valueof(qUser.Id) + String.valueof(quizQues.Id));
                }else{
                    wrapCandidate = new wrapCandidateDetails();
                }
                candidateDetailsList.add(wrapCandidate);
            }
            wrapResultReport.candidateDetails = candidateDetailsList;
            questionIndexCount = questionIndexCount + 1;
            resultReportList.add(wrapResultReport);
        }
        system.debug('resultReportList ====>'+resultReportList);
        return resultReportList;
    }
    public class wrapperResultReportQuestionWise{
        @AuraEnabled public String questionIndex='0';
        @AuraEnabled public String questionId='';
        @AuraEnabled public String questionName='';
		@AuraEnabled public String correctAnswerNameCombine='';
        @AuraEnabled public List<wrapCandidateDetails> candidateDetails = new List<wrapCandidateDetails>();
	}
    public class wrapCandidateDetails{
        @AuraEnabled public String userId='';
        @AuraEnabled public String userFullName='';
        @AuraEnabled public String selectedAnswerNameCombine='';
        @AuraEnabled public String isCorrect='';
    }



    //Start-----written by Sayantan----------
    @AuraEnabled
    public static List<SessionAnswerDetailsView> getAnswerWiseUserList(String sessionId){
        List<SessionAnswerDetailsView> returnList = new List<SessionAnswerDetailsView>();
        try {
            // List<AnswerSessionView> ansSessionViewList = new List<AnswerSessionView>();
            Quiz_Session__c session = [SELECT Id,isResultPublished__c,Quiz_Assessment_Name__c, Quiz_Assessment_Name__r.Name, Session_Join_Code__c,
                    Session_Name__c,Session_Status__c, Session_Time_Minutes__c 
                    FROM Quiz_Session__c WHERE ID=:sessionId];
            String assessmentID = session.Quiz_Assessment_Name__c;
            Map<ID,Quiz_Question__c> qustionMap = new Map<ID, Quiz_Question__c>( [SELECT ID, Name, Question__c,Quiz_Assessment_Name__c, 
                    isMultiAnswer__c,Quiz_Assessment_Name__r.Quiz_Admin_User__r.Name, Quiz_Assessment_Name__r.Name
                    /*(SELECT Id, Name, Answer__c, Index__c, isTrue__c, Quiz_Question__c FROM Quiz_Answers__r) ---- not takeing this line */
                    FROM Quiz_Question__c WHERE Quiz_Assessment_Name__c = :assessmentID]);
            List<Quiz_Result__c> answerList = [SELECT Id,Name, Quiz_User__c, Quiz_User__r.Name,JSON_Result__c, Quiz_User__r.Full_Name__c,
                    Quiz_User__r.Email__c, Quiz_Session__c 
                    FROM Quiz_Result__c WHERE Quiz_Session__c = :sessionId];
            Map<ID, List<Quiz_Answer__c>> answerMap = new Map<ID, List<Quiz_Answer__c>>();
            List<Quiz_Answer__c> relatedAnswerList = [SELECT ID, Name, Answer__c, Index__c, isTrue__c, Quiz_Question__c FROM Quiz_Answer__c WHERE Quiz_Question__c IN :qustionMap.keySet()];
            // for(String qid : qustionMap.keySet()){
            //     List<Quiz_Answer__c> answerList1 = new List<Quiz_Answer__c>();
            //     answerList1.addAll(qustionMap.get(qid).Quiz_Answers__r);
            //     answerMap.put(qid, answerList1);
            // }
            for(Quiz_Answer__c answer : relatedAnswerList){
                if (!answerMap.containsKey(answer.Quiz_Question__c))
                    answerMap.put(answer.Quiz_Question__c, new List<Quiz_Answer__c>());
                answerMap.get(answer.Quiz_Question__c).add(answer);
            }
            Map<ID, List<AnsUser>> quesIDvsListCorrectUser = new Map<ID, List<AnsUser>>();
            Map<ID, List<AnsUser>> quesIDvsListWrongUser = new Map<ID, List<AnsUser>>();
            Map<ID, List<Question>> quesIDvsListQuesAns = new Map<ID, List<Question>>();
            if(answerList != NULL && answerList.size()>0){
                Set<String> questionIDSet = new Set<String>();
                for(Quiz_Result__c qr : answerList){
                    // List<Map<String, Object>> answerMap = (List<Map<String,Object>>)JSON.deserializeUntyped(qr.JSON_Result__c);
                    // List<AnsUser> correctAnsUserList = new List<AnsUser>();
                    // List<AnsUser> wrongAnsUserList = new List<AnsUser>();
                    List<Question> questions = (List<Question>) JSON.deserialize(qr.JSON_Result__c, List<Question>.class);
                    // SessionAnswerDetailsView retObj = new SessionAnswerDetailsView();
                    System.debug('quiz result ----->'+qr);
                    for(Question qustion: questions){
                        System.debug('quiz result answer ----->'+qustion);
                        AnsUser ansUser = new AnsUser();
                        ansUser.userId = qr.Quiz_User__c;
                        ansUser.userName = qr.Quiz_User__r.Full_Name__c;
                        // retObj.quesId = qustion.quesId;
                        // retObj.question = qustion.questionName;// take this from question map.
                        // retObj.sessionId = sessionId;
                        // retObj.Quiz_Assessment_Name = qustionMap.get(qustion.quesId).Quiz_Assessment_Name__r.Name;
                        // System.debug('return object ---->'+retObj);
                        if(qustion.isAnswered){
                            System.debug('quiz result is answered ----->');
                            System.debug('answermap ----->'+answerMap.get(qustion.quesId));
                            if(qustion.isMultiAnswer){
                                System.debug('quiz result multi answer ----->');
                                Boolean correct=true;
                                // List<String> answerList1 = new List<String>();
                                for(Answer ans :  qustion.answerList){
                                    if((ans.isSelected && !ans.isTrue) ||(!ans.isSelected && ans.isTrue)){
                                        correct = false;
                                        System.debug('quiz result wrong answer selected ----->'+ans);
                                        break;
                                    //     if(!wrongAnsUserList.contains(ansUser))
                                    //         wrongAnsUserList.add(ansUser);
                                    //     correct = false;
                                    //     break;
                                    // }else if(!ans.isSelected && ans.isTrue){
                                    //     if(!wrongAnsUserList.contains(ansUser))
                                    //         wrongAnsUserList.add(ansUser);
                                    //     correct = false;
                                    //     break;
                                    }
                                }
                                if(correct){
                                    if(!quesIDvsListCorrectUser.containsKey(qustion.quesId))
                                        quesIDvsListCorrectUser.put(qustion.quesId, new List<AnsUser>());
                                    quesIDvsListCorrectUser.get(qustion.quesId).add(ansUser);
                                    System.debug('quiz result is answered and multi answer quesIDvsListCorrectUser ----->'+quesIDvsListCorrectUser);
                                }
                                else{
                                    if(!quesIDvsListWrongUser.containsKey(qustion.quesId))
                                        quesIDvsListWrongUser.put(qustion.quesId, new List<AnsUser>());
                                    quesIDvsListWrongUser.get(qustion.quesId).add(ansUser);
                                    System.debug('quiz result is answered and multi answer quesIDvsListCorrectUser ----->'+quesIDvsListCorrectUser);
                                }
                            }
                            //if(!retObj.isMultiAnswer){
                            else{
                                Boolean correct=false;
                                for(Answer ans : qustion.answerList){
                                    if(ans.isTrue && ans.isSelected){
                                        // correctAnsUserList.add(ansUser);
                                        System.debug('quiz result single answer right ----->'+ans);
                                        correct = true;
                                        break;
                                    }
                                    else{
                                        System.debug('quiz result single answer wrong ----->'+ans);
                                        correct = false;
                                    }
                                }
                                if(!correct){
                                    if(!quesIDvsListWrongUser.containsKey(qustion.quesId))
                                        quesIDvsListWrongUser.put(qustion.quesId, new List<AnsUser>());
                                    quesIDvsListWrongUser.get(qustion.quesId).add(ansUser);
                                    System.debug('quiz result single answer quesIDvsListWrongUser ----->'+quesIDvsListWrongUser);
                                }else{
                                    if(!quesIDvsListCorrectUser.containsKey(qustion.quesId))
                                        quesIDvsListCorrectUser.put(qustion.quesId, new List<AnsUser>());
                                    quesIDvsListCorrectUser.get(qustion.quesId).add(ansUser);
                                    System.debug('quiz result single answer quesIDvsListCorrectUser ---->'+quesIDvsListCorrectUser);
                                }
                                    // wrongAnsUserList.add(ansUser);

                            }
                        }
                        else{
                            // wrongAnsUserList.add(ansUser);
                            if(!quesIDvsListWrongUser.containsKey(qustion.quesId))
                                quesIDvsListWrongUser.put(qustion.quesId, new List<AnsUser>());
                            quesIDvsListWrongUser.get(qustion.quesId).add(ansUser);
                            System.debug('quiz result not answered quesIDvsListCorrectUser ----->'+quesIDvsListCorrectUser);
                            System.debug('quiz result not answered quesIDvsListWrongUser ------>'+quesIDvsListWrongUser);
                        }
                        // if(!quesIDvsListCorrectUser.containsKey(qustion.quesId))
                        //     quesIDvsListCorrectUser.put(qustion.quesId, new List<ansUser>());
                        // quesIDvsListCorrectUser.get(qustion.quesId).addAll(correctAnsUserList);
                        // if(!quesIDvsListWrongUser.containsKey(qustion.quesId))
                        //     quesIDvsListWrongUser.put(qustion.quesId, new List<ansUser>());
                        // quesIDvsListWrongUser.get(qustion.quesId).addAll(wrongAnsUserList);
                        // retObj.correctuserList = correctAnsUserList;
                        // retObj.wronguserList = wrongAnsUserList;
                        // returnList.add(retObj);
                        // System.debug('retObj final ---->'+retObj);
                        System.debug('final before return quesIDvsListCorrectUser --->'+quesIDvsListCorrectUser);
                        System.debug('final before return quesIDvsListWrongUser --->'+quesIDvsListWrongUser);
                        System.debug('final before return qustionMap --->'+qustionMap.get(qustion.quesId));
                    }
                }
            }
            // now create the return wraper based on question query. 
            for(String qid : qustionMap.keySet()){
                SessionAnswerDetailsView retObj = new SessionAnswerDetailsView();
                retObj.quesId = qid;
                retObj.correctuserList = quesIDvsListCorrectUser.get(qid);
                retObj.wronguserList = quesIDvsListWrongUser.get(qid);
                retObj.question = qustionMap.get(qid).Question__c;
                retObj.Quiz_Assessment_Name = qustionMap.get(qid).Quiz_Assessment_Name__r.Name;
                retObj.answerList = answerMap.get(qid);
                returnList.add(retObj);
            }
            System.debug('before return in try block returnList ====>'+returnList);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return returnList;
    }
    // public class ansJSONDeserialize
    public class Question {
        public String questionName; // need to remove later
        public Integer questionIndex;
        public String quesId;
        public Boolean markForReview;
        public Boolean isMultiAnswer;
        public Boolean isAnswered;
        public String error;
        public List<Answer> answerList;
    }

    public class Answer {
        public Boolean isTrue;
        public Boolean isSelected;
        public String answerName;
        public String answerIndex;
        public String answerId;
    }

    public class SessionAnswerDetailsView{
        @AuraEnabled public String quesId='';
        @AuraEnabled public String sessionId='';
        @AuraEnabled public String Quiz_Assessment_Name='';
        @AuraEnabled public String question='';
        @AuraEnabled public List<ansUser> correctuserList = new List<AnsUser>();
        @AuraEnabled public List<ansUser> wronguserList = new List<AnsUser>();
        @AuraEnabled public List<Quiz_Answer__c> answerList = new List<Quiz_Answer__c>();
        // @auraEnabled public List<Quiz_Answer__c> answerList = new List<Quiz_Answer__c>();

    }
    public class AnsUser{
        @AuraEnabled public String userName='';
        // @AuraEnabled public String userEmail='';
        @AuraEnabled public String userId='';
    }
    // Public class correctAnswer{
    //     @AuraEnabled public String answer='';
    //     @AuraEnabled public Boolean correctAnswer=false;
    //     @AuraEnabled public Boolean multiANser=false;
    //     @AuraEnabled public Boolean correctAnswer=false;
        
    // }
    //End-----written by Sayantan----------
}